apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-anti-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - httpd
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: httpd
        image: httpd:latest
